# Generated by Django 6.0.2 on 2026-02-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g., chinese-new-year-promo)', unique=True)),
                ('type', models.CharField(choices=[('BLOG', 'News & Events'), ('PROMO', 'Promotion')], max_length=10)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='marketing_uploads/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
