# Generated by Django 6.0.2 on 2026-02-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgallery',
            options={'verbose_name_plural': 'Event Galleries'},
        ),
    ]
