# Generated by Django 6.0.2 on 2026-02-12 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., VIP Room 1, Main Hall', max_length=100)),
                ('area_type', models.CharField(choices=[('VIP', 'VIP Room'), ('HALL', 'Main Dining Hall (Ala Carte)')], max_length=10)),
                ('capacity', models.IntegerField(help_text='Max pax for this room/area')),
                ('min_pax', models.IntegerField(default=1, help_text='Minimum pax required to book')),
                ('description', models.TextField(blank=True, help_text="e.g., 'Has KTV' or 'Ocean View'")),
                ('image', models.ImageField(blank=True, null=True, upload_to='dining_areas/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(help_text='Phone or Viber', max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('LUNCH', 'Lunch (11:00 AM - 2:30 PM)'), ('DINNER', 'Dinner (5:00 PM - 10:00 PM)')], max_length=10)),
                ('time', models.TimeField(help_text='Specific arrival time')),
                ('pax', models.IntegerField()),
                ('special_request', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dining_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.diningarea')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
