# Generated by Django 6.0.2 on 2026-02-14 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningarea',
            name='has_couch',
            field=models.BooleanField(default=False, verbose_name='Lounge Area / Couch'),
        ),
        migrations.AddField(
            model_name='diningarea',
            name='has_ktv',
            field=models.BooleanField(default=False, verbose_name='KTV'),
        ),
        migrations.AddField(
            model_name='diningarea',
            name='has_restroom',
            field=models.BooleanField(default=False, verbose_name='Private Restroom'),
        ),
        migrations.AddField(
            model_name='diningarea',
            name='has_tv',
            field=models.BooleanField(default=False, verbose_name='TV'),
        ),
        migrations.AlterField(
            model_name='diningarea',
            name='description',
            field=models.TextField(blank=True, help_text="e.g., 'Ocean View'"),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dining_areas/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='reservations.diningarea')),
            ],
        ),
    ]
