# Generated by Django 6.0.2 on 2026-02-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_diningarea_has_couch_diningarea_has_ktv_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
