# Generated by Django 6.0.2 on 2026-02-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_delete_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Has the 4-hour reminder been sent?'),
        ),
    ]
