# Generated by Django 6.0.2 on 2026-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('SEATED', 'Seated (Arrived)'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No-Show'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
