# Generated by Django 6.0.2 on 2026-02-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_customer_no_show_count_reservation_encoded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='Auto-tagged after 3 visits'),
        ),
        migrations.AddField(
            model_name='customer',
            name='visit_count',
            field=models.IntegerField(default=0, help_text='Total completed visits'),
        ),
    ]
