# Generated by Django 6.0.2 on 2026-02-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_customer_is_vip_customer_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='source',
            field=models.CharField(choices=[('WEB', 'Website'), ('WALK_IN', 'Walk-in'), ('PHONE', 'Phone Call'), ('SOCIAL', 'Social Media')], default='WEB', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('WEB', 'Website'), ('WALK_IN', 'Walk-in'), ('PHONE', 'Phone Call'), ('SOCIAL', 'Social Media')], default='WEB', max_length=20),
        ),
    ]
