# Generated by Django 6.0.2 on 2026-02-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_historicalreservation_source_reservation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningarea',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Consumable price in PHP', max_digits=10),
        ),
    ]
