# Generated by Django 6.0.2 on 2026-03-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_diningarea_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Used for automated birthday promos', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_birthday_promo_year',
            field=models.IntegerField(blank=True, help_text='Prevents sending multiple times a year', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_retention_sent',
            field=models.DateField(blank=True, help_text="When the last 'We Miss You' message was sent", null=True),
        ),
    ]
