# Generated by Django 6.0.2 on 2026-03-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_claimed_vip_perk',
            field=models.BooleanField(default=False, help_text='Has received the website welcome perk'),
        ),
    ]
