# Generated by Django 6.0.2 on 2026-03-03 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_customer_has_claimed_vip_perk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('points_required', models.IntegerField(help_text='How many points this costs')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['points_required'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='points_balance',
            field=models.IntegerField(default=0, help_text='Current available points'),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='final_bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total bill paid (for point calculation)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='points_earned',
            field=models.IntegerField(default=0, help_text='Points awarded for this specific visit'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='final_bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total bill paid (for point calculation)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='points_earned',
            field=models.IntegerField(default=0, help_text='Points awarded for this specific visit'),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('REDEEMED', 'Redeemed')], max_length=10)),
                ('points', models.IntegerField(help_text='Amount of points (e.g., 150)')),
                ('amount_spent', models.DecimalField(blank=True, decimal_places=2, help_text='If EARNED, the bill amount', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='reservations.customer')),
                ('encoded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, help_text='Null if walk-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='reservations.reservation')),
                ('reward_item', models.ForeignKey(blank=True, help_text='Filled if REDEEMED', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.rewarditem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
