# Generated by Django 6.0.2 on 2026-03-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_rewarditem_customer_points_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (To Claim)'), ('CLAIMED', 'Claimed / Served'), ('CANCELLED', 'Cancelled (Points Refunded)')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='reservations.customer')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reward_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.rewarditem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
