# Generated by Django 6.0.2 on 2026-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_rewardredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
