# Generated by Django 6.0.2 on 2026-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='care_of',
            field=models.CharField(blank=True, help_text='E.g., Care of Evelyn, Care of Austin', max_length=100, null=True),
        ),
    ]
