# Generated by Django 6.0.2 on 2026-08-20 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_customer_care_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='management_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='management_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
