# Generated by Django 6.0.2 on 2026-08-20 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_historicalreservation_management_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreservation',
            name='management_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='management_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
