export const translations = {
    en: {
        nav: { menu: "Menu", events: "Events", news: "News & Promos", rooms: "Private Rooms", about: "About Us", contact: "Contact", book: "Book a Table" },
        footer: { explore: "Explore", contact: "Contact", hours: "Hours", lunch: "Lunch", dinner: "Dinner", address: "Lot 3&4 Block A2, Diosdado Macapagal Blvd, CBP, Pasay City, Metro Manila", rights: "Golden Bay Restaurant. All Rights Reserved." },
        home: { back: "← Back to Experience", enter: "Enter Experience" },
        marketing: { all: "All Updates", promo: "Promotions", blog: "Events & Stories", readMore: "Read More", limited: "Limited Offer", event: "Event", back: "← Back to News" },
        menu: { title: "Our Menu", search: "Search by name, code, or ingredient...", all: "All", empty: "No dishes found matching", clear: "Clear Search", liveCatch: "Live Catch", seasonal: "Seasonal Price", styles: "Available Cooking Styles", standard: "Standard", market: "Market Price" },
        about: { title: "Our Story", since: "Since 2009", p1: "Golden Bay Fresh Seafoods Restaurant is a landmark culinary destination in Pasay City, dedicated to the art of fine Chinese dining.", p2: "We blend traditional techniques with modern innovation to provide an unparalleled experience centered around the freshest seafood delights. Every dish tells a story of heritage, quality, and passion.", vision: "Our Vision", vDesc: "To be the premier destination for seafood lovers, celebrating the bounty of the sea through innovative dishes and memorable experiences.", mission: "Our Mission", mDesc: "To deliver excellence in every aspect—from sourcing sustainable ingredients to providing attentive, personalized service that exceeds expectations.", values: "Core Values", val1: "Excellence", val1d: "Perfection in every detail.", val2: "Integrity", val2d: "Honest sourcing & standards.", val3: "Sustainability", val3d: "Stewards of the sea.", val4: "Innovation", val4d: "Redefining tradition.", val5: "Hospitality", val5d: "Every guest is royalty.", services: "Services", sTitle: "World-Class Experiences", sDesc: "From intimate gatherings to grand celebrations, we offer versatile spaces and services tailored to your needs.", s1: "Signature Seafood Menu", s2: "Private VIP Rooms", s3: "Grand Event Spaces", s4: "Premium Delivery", bookEvent: "Book Your Event" },
        vip: { title: "Private Dining", roomType1: "Exclusive Room", roomType2: "Dining Hall", noImage: "No Image", pax: "PAX", seatsLeft: "Seats Left:", maxCap: "Max Capacity:", booked: "Booked", full: "Full", stdSetup: "Standard Setup", ready: "Ready to reserve a private room?", book: "Book Reservation" },
        events: { title: "Event Inquiries", subtitle: "Celebrate With Us", desc: "Unrivaled scale and elegance. Let Golden Bay be the spectacular stage for your most significant milestones, from intimate gatherings to grand galas.", f1Title: "Grand Banquet Hall", f1Desc: "Our expansive, pillar-less Grand Banquet Hall is engineered to host spectacular, large-scale celebrations for up to 800 guests.", f2Title: "Versatile Spaces", f2Desc: "Host up to 200 guests in our converted Main Dining mini-banquet, or enjoy an exclusive gathering for 60 in our premier VIP Manila room.", f3Title: "Modern LED Visuals", f3Desc: "Newly installed, state-of-the-art LED walls provide stunning visual clarity for presentations and event ambiance.", connect: "Connect With Our Specialists", cDesc: "Due to the bespoke nature of customized events, we prefer to speak with you directly. Contact our dedicated event team to discuss availability, menus, and logistics.", direct: "Direct Line", emailInq: "Email Inquiries", instant: "Instant Messaging", via: "Connect via WeChat or Viber", faqTitle: "Event Details" },
        contact: { title: "Location & Contact", getTouch: "Get in Touch", cDesc: "Whether you have a question about our menu, need assistance finding us, or wish to inquire about corporate partnerships, our team is at your service.", addrLabel: "Address", resInq: "Reservations & Inquiries", emailLabel: "Email", hoursLabel: "Operating Hours" },
        reservation: { title: "Reservations", details: "Details", selectPref: "Select your preferred date and experience.", bookWechat: "Book via WeChat", vipRooms: "VIP Private Rooms", alaCarte: "Ala Carte Dining", checking: "Checking availability...", confirmTitle: "Confirm Details", fName: "Full Name", fContact: "Contact / Viber", fEmail: "Email (Optional)", fGuests: "Number of Guests", fTime: "Arrival Time", selTime: "Select Preferred Time", fNotes: "Special Request / Menu Preferences", proc: "Processing Request...", reqRes: "Request Reservation", wechatTitle: "Book via WeChat", scan: "Scan this code to chat directly with our reservation specialist.", retWeb: "Return to Web Booking", reqPend: "Request Pending", rev: "We are reviewing your details", allow: "Please allow up to 30 minutes for confirmation.", retHome: "Return to Home" }
    },
    zh: {
        nav: { menu: "菜单", events: "活动", news: "新闻与优惠", rooms: "贵宾包厢", about: "关于我们", contact: "联系我们", book: "预订餐桌" },
        footer: { explore: "探索", contact: "联系", hours: "营业时间", lunch: "午餐", dinner: "晚餐", address: "帕赛市 Diosdado Macapagal 大道", rights: "金海湾海鲜酒家。保留所有权利。" },
        home: { back: "← 返回体验", enter: "开启体验" },
        marketing: { all: "全部动态", promo: "优惠促销", blog: "活动与故事", readMore: "阅读更多", limited: "限时优惠", event: "活动", back: "← 返回新闻" },
        menu: { title: "我们的菜单", search: "按名称、代码或成分搜索...", all: "全部", empty: "未找到匹配的菜品", clear: "清除搜索", liveCatch: "生猛海鲜", seasonal: "时价", styles: "可选烹饪方式", standard: "标准", market: "时价" },
        about: { title: "品牌故事", since: "始于 2009", p1: "金海湾海鲜大酒楼是帕赛市地标性的美食胜地，致力于提供高级中式餐饮的艺术体验。", p2: "我们将传统技艺与现代创新相结合，围绕最新鲜的海鲜美味提供无与伦比的体验。每一道菜都讲述着传承、品质与激情的故事。", vision: "我们的愿景", vDesc: "成为海鲜爱好者的首选目的地，通过创新菜肴和难忘体验庆祝海洋的馈赠。", mission: "我们的使命", mDesc: "在每个环节提供卓越体验——从采购可持续食材到提供超越期望的贴心个性化服务。", values: "核心价值观", val1: "卓越", val1d: "细节尽善尽美。", val2: "诚信", val2d: "诚信采购与高标准。", val3: "可持续", val3d: "海洋的守护者。", val4: "创新", val4d: "重新定义传统。", val5: "好客", val5d: "宾至如归。", services: "服务", sTitle: "世界级的体验", sDesc: "从私人聚会到盛大庆典，我们提供多功能空间和量身定制的服务。", s1: "招牌海鲜菜单", s2: "贵宾专属包厢", s3: "盛大宴会空间", s4: "尊享外送服务", bookEvent: "预订您的活动" },
        vip: { title: "尊享私宴", roomType1: "专属包厢", roomType2: "大厅散座", noImage: "暂无图片", pax: "人", seatsLeft: "剩余座位:", maxCap: "最大容纳:", booked: "已满", full: "客满", stdSetup: "标准配置", ready: "准备预订包厢吗？", book: "立即预订" },
        events: { title: "活动咨询", subtitle: "与我们共庆", desc: "无与伦比的规模与优雅。让金海湾成为您重要里程碑的壮丽舞台，无论是私密聚会还是盛大晚宴。", f1Title: "豪华宴会厅", f1Desc: "我们宽敞的无柱大宴会厅专为举办多达800人的盛大庆典而设计。", f2Title: "多功能空间", f2Desc: "主餐厅可转换为容纳200人的小型宴会厅，或在我们的顶级马尼拉贵宾室享受60人的专属聚会。", f3Title: "现代LED视觉设备", f3Desc: "全新安装的最先进LED屏幕，为演示和活动氛围提供令人惊叹的视觉清晰度。", connect: "联系我们的专家", cDesc: "由于定制活动的独特性，我们更倾向于与您直接沟通。请联系我们的专属活动团队，讨论场地、菜单和后勤事宜。", direct: "直线电话", emailInq: "邮件咨询", instant: "即时通讯", via: "通过微信或Viber联系", faqTitle: "活动详情" },
        contact: { title: "位置与联系方式", getTouch: "联系我们", cDesc: "无论您对菜单有疑问、需要寻路指引，还是希望咨询企业合作，我们的团队随时为您服务。", addrLabel: "地址", resInq: "预订与咨询", emailLabel: "电子邮件", hoursLabel: "营业时间" },
        reservation: { title: "预订座位", details: "预订详情", selectPref: "选择您的首选日期和体验。", bookWechat: "通过微信预订", vipRooms: "贵宾包厢", alaCarte: "大厅散座", checking: "正在查询...", confirmTitle: "确认详情", fName: "全名", fContact: "联系电话 / Viber", fEmail: "电子邮件 (选填)", fGuests: "就餐人数", fTime: "预计到达时间", selTime: "选择时间", fNotes: "特殊要求 / 饮食偏好", proc: "处理中...", reqRes: "提交预订", wechatTitle: "微信预订", scan: "扫描此二维码，直接与我们的预订专员沟通。", retWeb: "返回网页预订", reqPend: "预订已提交", rev: "我们正在审核您的预订信息", allow: "请耐心等待最多30分钟的确认通知。", retHome: "返回首页" }
    },
    zh_hant: {
        nav: { menu: "菜單", events: "活動", news: "新聞與優惠", rooms: "貴賓包廂", about: "關於我們", contact: "聯繫我們", book: "預訂餐桌" },
        footer: { explore: "探索", contact: "聯繫", hours: "營業時間", lunch: "午餐", dinner: "晚餐", address: "帕賽市 Diosdado Macapagal 大道", rights: "金海灣海鮮酒家。保留所有權利。" },
        home: { back: "← 返回體驗", enter: "開啟體驗" },
        marketing: { all: "全部動態", promo: "優惠促銷", blog: "活動與故事", readMore: "閱讀更多", limited: "限時優惠", event: "活動", back: "← 返回新聞" },
        menu: { title: "我們的菜單", search: "按名稱、代碼或成分搜索...", all: "全部", empty: "未找到匹配的菜品", clear: "清除搜索", liveCatch: "生猛海鮮", seasonal: "時價", styles: "可選烹飪方式", standard: "標準", market: "時價" },
        about: { title: "品牌故事", since: "始於 2009", p1: "金海灣海鮮大酒樓是帕賽市地標性的美食勝地，致力於提供高級中式餐飲的藝術體驗。", p2: "我們將傳統技藝與現代創新相結合，圍繞最新鮮的海鮮美味提供無與倫比的體驗。每一道菜都講述著傳承、品質與激情的故事。", vision: "我們的願景", vDesc: "成為海鮮愛好者的首選目的地，通過創新菜餚和難忘體驗慶祝海洋的饋贈。", mission: "我們的使命", mDesc: "在每個環節提供卓越體驗——從採購可持續食材到提供超越期望的貼心個性化服務。", values: "核心價值觀", val1: "卓越", val1d: "細節盡善盡美。", val2: "誠信", val2d: "誠信採購與高標準。", val3: "可持續", val3d: "海洋的守護者。", val4: "創新", val4d: "重新定義傳統。", val5: "好客", val5d: "賓至如歸。", services: "服務", sTitle: "世界級的體驗", sDesc: "從私人聚會到盛大慶典，我們提供多功能空間和量身定制的服務。", s1: "招牌海鮮菜單", s2: "貴賓專屬包廂", s3: "盛大宴會空間", s4: "尊享外送服務", bookEvent: "預訂您的活動" },
        vip: { title: "尊享私宴", roomType1: "專屬包廂", roomType2: "大廳散座", noImage: "暫無圖片", pax: "人", seatsLeft: "剩餘座位:", maxCap: "最大容納:", booked: "已滿", full: "客滿", stdSetup: "標準配置", ready: "準備預訂包廂嗎？", book: "立即預訂" },
        events: { title: "活動諮詢", subtitle: "與我們共慶", desc: "無與倫比的規模與優雅。讓金海灣成為您重要里程碑的壯麗舞台，無論是私密聚會還是盛大晚宴。", f1Title: "豪華宴會廳", f1Desc: "我們寬敞的無柱大宴會廳專為舉辦多達800人的盛大慶典而設計。", f2Title: "多功能空間", f2Desc: "主餐廳可轉換為容納200人的小型宴會廳，或在我們的頂級馬尼拉貴賓室享受60人的專屬聚會。", f3Title: "現代LED視覺設備", f3Desc: "全新安裝的最先進LED屏幕，為演示和活動氛圍提供令人驚嘆的視覺清晰度。", connect: "聯繫我們的專家", cDesc: "由於定制活動的獨特性，我們更傾向於與您直接溝通。請聯繫我們的專屬活動團隊，討論場地、菜單和後勤事宜。", direct: "直線電話", emailInq: "郵件諮詢", instant: "即時通訊", via: "通過微信或Viber聯繫", faqTitle: "活動詳情" },
        contact: { title: "位置與聯繫方式", getTouch: "聯繫我們", cDesc: "無論您對菜單有疑問、需要尋路指引，還是希望諮詢企業合作，我們的團隊隨時為您服務。", addrLabel: "地址", resInq: "預訂與諮詢", emailLabel: "電子郵件", hoursLabel: "營業時間" },
        reservation: { title: "預訂座位", details: "預訂詳情", selectPref: "選擇您的首選日期和體驗。", bookWechat: "通過微信預訂", vipRooms: "貴賓包廂", alaCarte: "大廳散座", checking: "正在查詢...", confirmTitle: "確認詳情", fName: "全名", fContact: "聯繫電話 / Viber", fEmail: "電子郵件 (選填)", fGuests: "就餐人數", fTime: "預計到達時間", selTime: "選擇時間", fNotes: "特殊要求 / 飲食偏好", proc: "處理中...", reqRes: "提交預訂", wechatTitle: "微信預訂", scan: "掃描此二維碼，直接與我們的預訂專員溝通。", retWeb: "返回網頁預訂", reqPend: "預訂已提交", rev: "我們正在審核您的預訂信息", allow: "請耐心等待最多30分鐘的確認通知。", retHome: "返回首頁" }
    },
    ja: {
        nav: { menu: "メニュー", events: "イベント", news: "ニュース＆プロモ", rooms: "個室", about: "私たちについて", contact: "お問い合わせ", book: "予約する" },
        footer: { explore: "探索", contact: "連絡先", hours: "営業時間", lunch: "ランチ", dinner: "ディナー", address: "パサイ市 ディオスダド・マカパガル大通り", rights: "ゴールデンベイ レストラン。全著作権所有。" },
        home: { back: "← 体験に戻る", enter: "体験を始める" },
        marketing: { all: "すべての更新", promo: "プロモーション", blog: "イベントとストーリー", readMore: "続きを読む", limited: "限定オファー", event: "イベント", back: "← ニュースに戻る" },
        menu: { title: "メニュー", search: "名前、コード、または材料で検索...", all: "すべて", empty: "料理が見つかりません", clear: "検索をクリア", liveCatch: "活魚", seasonal: "時価", styles: "調理方法", standard: "標準", market: "時価" },
        about: { title: "私たちの物語", since: "2009年以来", p1: "ゴールデンベイ・フレッシュシーフード・レストランは、パサイ市にある高級中華料理のアートに捧げられた画期的な目的地です。", p2: "私たちは伝統的な技術と革新を融合させ、最も新鮮なシーフードを中心に比類のない体験を提供します。すべての料理には伝統、品質、そして情熱の物語があります。", vision: "私たちのビジョン", vDesc: "シーフード愛好家のための最高の目的地となり、革新的な料理と思い出に残る体験を通じて海の恵みを祝福すること。", mission: "私たちの使命", mDesc: "持続可能な食材の調達から、期待を超えるパーソナライズされたサービスの提供まで、すべての面で卓越性を提供すること。", values: "コアバリュー", val1: "卓越性", val1d: "細部に至るまでの完璧さ。", val2: "誠実さ", val2d: "正直な調達と基準。", val3: "持続可能性", val3d: "海の管理者。", val4: "革新", val4d: "伝統の再定義。", val5: "おもてなし", val5d: "すべてのお客様を王族のように。", services: "サービス", sTitle: "世界クラスの体験", sDesc: "親密な集まりから壮大な祝賀会まで、お客様のニーズに合わせた多目的な空間とサービスを提供します。", s1: "シグネチャーシーフードメニュー", s2: "プライベートVIPルーム", s3: "壮大なイベントスペース", s4: "プレミアムデリバリー", bookEvent: "イベントを予約する" },
        vip: { title: "プライベートダイニング", roomType1: "個室", roomType2: "ダイニングホール", noImage: "画像なし", pax: "名様", seatsLeft: "残り席数:", maxCap: "最大定員:", booked: "予約済", full: "満席", stdSetup: "標準セットアップ", ready: "個室を予約する準備はできましたか？", book: "予約する" },
        events: { title: "イベントのお問い合わせ", subtitle: "私たちと一緒に祝う", desc: "比類のない規模と優雅さ。親密な集まりから壮大なガラまで、ゴールデンベイを最も重要なマイルストーンのための壮大なステージにしましょう。", f1Title: "グランドバンケットホール", f1Desc: "私たちの広々とした柱のないグランドバンケットホールは、最大800名様までの壮大な大規模なお祝いを主催するように設計されています。", f2Title: "多目的なスペース", f2Desc: "最大200名様までのメインダイニングをミニバンケットに変換したり、最高級のVIPマニラルームで60名様向けの特別な集まりをお楽しみください。", f3Title: "最新のLEDビジュアル", f3Desc: "新しく設置された最先端のLEDウォールは、プレゼンテーションやイベントの雰囲気に驚くほどの視覚的な明瞭さを提供します。", connect: "スペシャリストとつながる", cDesc: "カスタマイズされたイベントのオーダーメイドの性質上、直接お話しすることをお勧めします。空き状況、メニュー、ロジスティクスについては、専任のイベントチームにお問い合わせください。", direct: "直通ダイヤル", emailInq: "メールでのお問い合わせ", instant: "インスタントメッセージング", via: "WeChatまたはViber経由で接続", faqTitle: "イベントの詳細" },
        contact: { title: "場所と連絡先", getTouch: "お問い合わせ", cDesc: "メニューに関するご質問、道案内が必要な場合、または企業パートナーシップに関するお問い合わせなど、私たちのチームが対応いたします。", addrLabel: "住所", resInq: "予約と問い合わせ", emailLabel: "メール", hoursLabel: "営業時間" },
        reservation: { title: "ご予約", details: "詳細", selectPref: "ご希望の日付と体験を選択してください。", bookWechat: "WeChatで予約", vipRooms: "VIP個室", alaCarte: "アラカルトダイニング", checking: "空き状況を確認中...", confirmTitle: "詳細を確認", fName: "フルネーム", fContact: "連絡先 / Viber", fEmail: "メールアドレス (任意)", fGuests: "ゲストの数", fTime: "到着時間", selTime: "希望の時間を選択", fNotes: "特別なご要望 / メニューの好み", proc: "リクエストを処理中...", reqRes: "予約をリクエストする", wechatTitle: "WeChatで予約", scan: "このコードをスキャンして、予約スペシャリストと直接チャットしてください。", retWeb: "Web予約に戻る", reqPend: "リクエスト保留中", rev: "詳細を確認しています", allow: "確認まで最大30分お待ちください。", retHome: "ホームに戻る" }
    },
    ko: {
        nav: { menu: "메뉴", events: "이벤트", news: "뉴스 및 프로모션", rooms: "프라이빗 룸", about: "소개", contact: "연락처", book: "테이블 예약" },
        footer: { explore: "둘러보기", contact: "연락처", hours: "영업 시간", lunch: "점심", dinner: "저녁", address: "파사이 시티, 디오스다도 마카파갈 대로", rights: "골든 베이 레스토랑. 모든 권리 보유." },
        home: { back: "← 체험으로 돌아가기", enter: "체험 시작" },
        marketing: { all: "모든 소식", promo: "프로모션", blog: "이벤트 및 스토리", readMore: "더 보기", limited: "한정 혜택", event: "이벤트", back: "← 뉴스로 돌아가기" },
        menu: { title: "메뉴", search: "이름, 코드 또는 재료로 검색...", all: "전체", empty: "일치하는 요리를 찾을 수 없습니다", clear: "검색 지우기", liveCatch: "활어", seasonal: "시가", styles: "조리 방식", standard: "기본", market: "시가" },
        about: { title: "우리의 이야기", since: "2009년 설립", p1: "골든 베이 프레시 씨푸드 레스토랑은 파사이 시티의 랜드마크이자 고급 중식 다이닝의 예술을 선보이는 곳입니다.", p2: "우리는 전통적인 기술과 현대적인 혁신을 결합하여 가장 신선한 해산물을 중심으로 타의 추종을 불허하는 경험을 제공합니다. 모든 요리에는 전통, 품질 및 열정의 이야기가 담겨 있습니다.", vision: "우리의 비전", vDesc: "혁신적인 요리와 기억에 남는 경험을 통해 바다의 풍요로움을 축하하는 해산물 애호가들을 위한 최고의 목적지가 되는 것.", mission: "우리의 사명", mDesc: "지속 가능한 식재료 조달부터 기대를 뛰어넘는 세심하고 맞춤화된 서비스 제공에 이르기까지 모든 면에서 탁월함을 제공합니다.", values: "핵심 가치", val1: "탁월함", val1d: "모든 디테일의 완벽함.", val2: "무결성", val2d: "정직한 조달 및 표준.", val3: "지속 가능성", val3d: "바다의 관리자.", val4: "혁신", val4d: "전통의 재정의.", val5: "환대", val5d: "모든 고객을 왕족처럼.", services: "서비스", sTitle: "세계적인 수준의 경험", sDesc: "소규모 모임부터 성대한 축하 행사까지, 고객의 요구에 맞춘 다목적 공간과 서비스를 제공합니다.", s1: "시그니처 해산물 메뉴", s2: "프라이빗 VIP 룸", s3: "그랜드 이벤트 공간", s4: "프리미엄 배달", bookEvent: "이벤트 예약하기" },
        vip: { title: "프라이빗 다이닝", roomType1: "독점 룸", roomType2: "다이닝 홀", noImage: "이미지 없음", pax: "명", seatsLeft: "남은 좌석:", maxCap: "최대 수용 인원:", booked: "예약됨", full: "만석", stdSetup: "기본 설정", ready: "프라이빗 룸을 예약하시겠습니까?", book: "예약하기" },
        events: { title: "이벤트 문의", subtitle: "우리와 함께 축하하세요", desc: "타의 추종을 불허하는 규모와 우아함. 소규모 모임부터 성대한 갈라에 이르기까지, 골든 베이가 가장 중요한 이정표를 위한 장대한 무대가 되도록 하십시오.", f1Title: "그랜드 연회장", f1Desc: "기둥이 없는 넓은 그랜드 연회장은 최대 800명의 게스트를 수용할 수 있는 성대하고 대규모의 축하 행사를 주최하도록 설계되었습니다.", f2Title: "다목적 공간", f2Desc: "메인 다이닝 미니 연회장에서 최대 200명의 게스트를 수용하거나, 프리미어 VIP 마닐라 룸에서 60명을 위한 독점적인 모임을 즐기십시오.", f3Title: "최신 LED 비주얼", f3Desc: "새로 설치된 최첨단 LED 월은 프레젠테이션 및 이벤트 분위기를 위해 놀라운 시각적 선명도를 제공합니다.", connect: "전문가와 연결하기", cDesc: "맞춤형 이벤트의 특성상 직접 상담하는 것을 선호합니다. 전담 이벤트 팀에 연락하여 예약 가능 여부, 메뉴 및 세부 사항을 논의하십시오.", direct: "직통 전화", emailInq: "이메일 문의", instant: "인스턴트 메시징", via: "WeChat 또는 Viber를 통한 연결", faqTitle: "이벤트 세부 정보" },
        contact: { title: "위치 및 연락처", getTouch: "연락하기", cDesc: "메뉴에 대한 질문이 있거나, 길 안내가 필요하거나, 기업 파트너십에 대해 문의하고 싶으시다면 저희 팀이 도와드리겠습니다.", addrLabel: "주소", resInq: "예약 및 문의", emailLabel: "이메일", hoursLabel: "영업 시간" },
        reservation: { title: "예약", details: "세부 정보", selectPref: "원하는 날짜와 경험을 선택하십시오.", bookWechat: "WeChat을 통한 예약", vipRooms: "VIP 프라이빗 룸", alaCarte: "알라카르트 다이닝", checking: "예약 가능 여부 확인 중...", confirmTitle: "세부 정보 확인", fName: "성명", fContact: "연락처 / Viber", fEmail: "이메일 (선택 사항)", fGuests: "게스트 수", fTime: "도착 시간", selTime: "원하는 시간 선택", fNotes: "특별 요청 / 메뉴 기본 설정", proc: "요청 처리 중...", reqRes: "예약 요청", wechatTitle: "WeChat을 통한 예약", scan: "이 코드를 스캔하여 예약 전문가와 직접 채팅하십시오.", retWeb: "웹 예약으로 돌아가기", reqPend: "요청 대기 중", rev: "세부 정보를 검토 중입니다", allow: "확인까지 최대 30분이 소요될 수 있습니다.", retHome: "홈으로 돌아가기" }
    }
};