# Generated by Django 6.0.2 on 2026-02-12 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_chef_recommendation',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chinese Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='Order to display on menu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='code',
            field=models.CharField(blank=True, help_text='e.g., BA01', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_zh',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chinese Name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.CreateModel(
            name='MenuItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='Regular', help_text='e.g., S, M, L, Half, Whole', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_seasonal', models.BooleanField(default=False, help_text="If checked, price will show as 'Seasonal Price'")),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='menu.menuitem')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
