# Generated by Django 6.0.2 on 2026-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_cookingmethod_alter_category_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Japanese'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ko',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Korean'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Traditional Chinese'),
        ),
        migrations.AddField(
            model_name='cookingmethod',
            name='name_ja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cookingmethod',
            name='name_ko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cookingmethod',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ja',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Japanese'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ko',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Korean'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Traditional Chinese'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_zh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Simplified Chinese'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name_zh',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Simplified Chinese'),
        ),
    ]
